version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/maxbrunsfeld/counterfeiter/v6
    versions:
    - 6.3.0
    - 6.4.0
  - dependency-name: k8s.io/code-generator
    versions:
    - 0.20.2
    - 0.20.3
    - 0.20.4
    - 0.20.5
  - dependency-name: k8s.io/apimachinery
    versions:
    - 0.20.2
    - 0.20.3
    - 0.20.4
    - 0.20.5
  - dependency-name: k8s.io/api
    versions:
    - 0.20.2
    - 0.20.3
    - 0.20.4
    - 0.20.5
  - dependency-name: k8s.io/client-go
    versions:
    - 0.20.2
    - 0.20.3
    - 0.20.4
    - 0.20.5
  - dependency-name: github.com/spf13/cobra
    versions:
    - 1.1.1
    - 1.1.2
  - dependency-name: github.com/google/go-cmp
    versions:
    - 0.5.4
